### PR TITLE
Fix a code example

### PR DESCRIPTION
**Pull request by ParadoxOrigins**
Hey ! First, allow me to say that this module is awesome ^w^, but along the few things bothering me there is one HUGE thing: The code example to get an anime from URLs.

Kinda confusing for starters as `getInfoFromName()` will use the given URL as a name and not a URL ^

### CODE REVIEW

**Comment by Kylart** [comment]
Hey, Thanks!

That was indeed a bad typo from me, thank you for correcting it 😄

**Comment by ParadoxOrigins** [comment]
Actually, mind if at some point, i write some detailed docs with stuff like information about the structure of the returned data?

**Comment by Kylart** [comment]
Sure not! In fact, I would love to have a detailed docs but I just cannot afford

**Comment by ParadoxOrigins** [comment]
Alright, i'll try to write it over the next weeks then uwu

**Pull request merged**
